# Schema for the CLI
name: go-cli
version: 0.1
configFlag: config
description: An example CLI app written using Go.
flags:
  - name: config
    description: Path to configuration file.
    default: config.json

  - name: gopher
    description: Show something awesome!

subcommands:
  - name: greet
    description: Get a greeting.
    flags:
      - name: name
        description: Specify a custom name.
